/**
 * Base de conocimiento: Photoshop / Illustrator -> Affinity Photo / Designer / Publisher
 *
 * Cada entrada representa un concepto, herramienta o flujo de trabajo del
 * ecosistema Adobe y su equivalente (o la ruta de trabajo más cercana) en
 * el ecosistema Affinity (Serif).
 *
 * confidence:
 *   "estable"   -> equivalencia directa, nombre/ubicación estable entre versiones recientes
 *   "similar"   -> el concepto existe pero el flujo de trabajo difiere
 *   "workaround"-> Affinity no tiene el feature 1:1; se describe la forma de lograr el mismo resultado
 *   "verificar" -> la ubicación exacta puede variar según la versión de Affinity instalada
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.AffinityKB = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  const KB = [
    // ---------------- INTERFAZ / CONCEPTOS GENERALES ----------------
    {
      id: "workspace",
      source_app: "Photoshop/Illustrator",
      category: "Interfaz",
      aliases: ["workspace", "espacio de trabajo", "personas"],
      affinity_app: "Affinity (todas)",
      equivalent: "Personas (Personas)",
      location: "Barra superior: iconos de Persona (Foto, Desarrollo, Liquify, Retoque, Exportar, etc.)",
      shortcut: "N/A",
      notes:
        "Affinity divide el flujo de trabajo en 'Personas' en vez de paneles/espacios de trabajo sueltos. Cada Persona reconfigura toda la interfaz para una tarea (revelado RAW, retoque, liquify, exportación).",
      confidence: "similar",
    },
    {
      id: "smart-object",
      source_app: "Photoshop",
      category: "Capas",
      aliases: ["smart object", "objeto inteligente", "objeto avanzado"],
      affinity_app: "Affinity Photo",
      equivalent: "Documentos hijos embebidos + capas de Live Filter",
      location: "Capa > Nuevo documento embebido / File > Place (Linked)",
      shortcut: "N/A",
      notes:
        "No existe un 'Smart Object' idéntico. Para no-destructividad: usa capas de ajuste en vivo, Live Filters, y coloca imágenes como 'Linked' (enlazadas) en vez de incrustadas para poder editarlas desde el archivo original.",
      confidence: "workaround",
    },
    {
      id: "adjustment-layer",
      source_app: "Photoshop",
      category: "Ajustes",
      aliases: ["adjustment layer", "capa de ajuste"],
      affinity_app: "Affinity Photo",
      equivalent: "Capas de ajuste (Adjustment Layers)",
      location: "Panel Capas > botón 'Añadir capa de ajuste', o Layer > New Adjustment Layer",
      shortcut: "Igual concepto, icono de círculo medio relleno en el panel Capas",
      notes: "Equivalencia casi 1:1. Ambos son no destructivos y aceptan máscaras.",
      confidence: "estable",
    },
    {
      id: "layer-mask",
      source_app: "Photoshop",
      category: "Capas",
      aliases: ["layer mask", "máscara de capa", "mascara de capa"],
      affinity_app: "Affinity Photo",
      equivalent: "Máscara de capa",
      location: "Panel Capas > botón de máscara (icono rectángulo con círculo)",
      shortcut: "Pintar con negro/blanco igual que en Photoshop",
      notes: "Comportamiento idéntico: negro oculta, blanco revela, grises = transparencia parcial.",
      confidence: "estable",
    },
    {
      id: "clipping-mask",
      source_app: "Photoshop/Illustrator",
      category: "Capas",
      aliases: ["clipping mask", "máscara de recorte", "mascara de recorte"],
      affinity_app: "Affinity Photo/Designer",
      equivalent: "Clip to Layer Below",
      location: "Clic derecho sobre la capa > 'Clip to Layer Below', o arrastrar capa mientras mantienes Alt/Opción",
      shortcut: "Ctrl/Cmd+Alt+G (igual atajo que Photoshop)",
      notes: "El atajo se mantiene igual, lo que facilita mucho la transición.",
      confidence: "estable",
    },
    {
      id: "content-aware-fill",
      source_app: "Photoshop",
      category: "Retoque",
      aliases: ["content aware fill", "relleno según el contenido"],
      affinity_app: "Affinity Photo",
      equivalent: "Inpainting Brush Tool",
      location: "Persona de Retoque (Retouch Persona) > Inpainting Brush",
      shortcut: "J (dentro de Retouch Persona)",
      notes:
        "El resultado es comparable pero se pinta manualmente sobre el área a reconstruir en vez de hacer una selección + un solo clic.",
      confidence: "similar",
    },
    {
      id: "healing-brush",
      source_app: "Photoshop",
      category: "Retoque",
      aliases: ["healing brush", "pincel corrector", "spot healing"],
      affinity_app: "Affinity Photo",
      equivalent: "Healing Brush Tool / Patch Tool",
      location: "Persona de Retoque",
      shortcut: "J / H",
      notes: "Muy parecido en comportamiento y control de dureza/tamaño de pincel.",
      confidence: "estable",
    },
    {
      id: "liquify",
      source_app: "Photoshop",
      category: "Deformación",
      aliases: ["liquify", "licuar"],
      affinity_app: "Affinity Photo",
      equivalent: "Liquify Persona",
      location: "Icono de Persona 'Liquify' en la barra superior",
      shortcut: "N/A",
      notes: "En vez de un filtro modal, es una Persona completa con sus propias herramientas (Push, Twirl, Pinch, etc.).",
      confidence: "estable",
    },
    {
      id: "puppet-warp",
      source_app: "Photoshop",
      category: "Deformación",
      aliases: ["puppet warp", "deformar marioneta"],
      affinity_app: "Affinity Photo/Designer",
      equivalent: "Mesh Warp Tool",
      location: "Herramientas > Mesh Warp",
      shortcut: "N/A",
      notes: "Usa una malla de rejilla en vez de 'pines' articulados; el control es más manual pero logra resultados similares.",
      confidence: "similar",
    },
    {
      id: "camera-raw",
      source_app: "Photoshop",
      category: "RAW",
      aliases: ["camera raw", "adobe camera raw", "acr"],
      affinity_app: "Affinity Photo",
      equivalent: "Develop Persona",
      location: "Se abre automáticamente al importar un archivo RAW, o icono de Persona 'Develop'",
      shortcut: "N/A",
      notes: "Controles equivalentes: White Balance, Tone Curve, Detail (nitidez/ruido), Lens Corrections, todos presentes.",
      confidence: "estable",
    },
    {
      id: "blend-modes",
      source_app: "Photoshop/Illustrator",
      category: "Capas",
      aliases: ["blend mode", "modo de fusión", "modos de fusión"],
      affinity_app: "Affinity (todas)",
      equivalent: "Blend Mode (mismo nombre)",
      location: "Parte superior del panel Capas, menú desplegable",
      shortcut: "N/A",
      notes: "Los nombres de los modos (Multiply, Screen, Overlay, etc.) son idénticos.",
      confidence: "estable",
    },
    {
      id: "layer-styles",
      source_app: "Photoshop",
      category: "Efectos",
      aliases: ["layer style", "estilo de capa", "drop shadow", "bevel and emboss"],
      affinity_app: "Affinity Photo/Designer",
      equivalent: "Layer Effects (FX)",
      location: "Panel Capas > botón 'fx' al pie, o clic derecho > 'Layer Effects'",
      shortcut: "N/A",
      notes: "Mismo set de efectos: Sombra, Resplandor, Bisel, Contorno, Relleno degradado, etc. El diálogo es muy parecido.",
      confidence: "estable",
    },
    {
      id: "actions",
      source_app: "Photoshop",
      category: "Automatización",
      aliases: ["actions", "acciones", "batch"],
      affinity_app: "Affinity Photo",
      equivalent: "Macros (panel Library)",
      location: "Panel Library > Macro > Record Macro",
      shortcut: "N/A",
      notes:
        "Se graban igual que las Acciones de Photoshop. Para procesar lotes de archivos: File > New Batch Job.",
      confidence: "similar",
    },
    {
      id: "frequency-separation",
      source_app: "Photoshop",
      category: "Retoque avanzado",
      aliases: ["frequency separation", "separación de frecuencias"],
      affinity_app: "Affinity Photo",
      equivalent: "Workflow manual: High Pass (Live Filter) + Gaussian Blur",
      location: "Filters > Sharpen > High Pass (como capa en modo Live) + duplicar y aplicar Gaussian Blur en la otra capa",
      shortcut: "N/A",
      notes: "No hay un botón dedicado; se arma el mismo stack de dos capas manualmente. El resultado final es idéntico.",
      confidence: "workaround",
    },
    {
      id: "dodge-burn",
      source_app: "Photoshop",
      category: "Retoque",
      aliases: ["dodge tool", "burn tool", "sobreexponer", "subexponer"],
      affinity_app: "Affinity Photo",
      equivalent: "Dodge Brush / Burn Brush",
      location: "Persona de Retoque",
      shortcut: "Mismos nombres de herramienta",
      notes: "Comportamiento y rangos (Shadows/Midtones/Highlights) equivalentes.",
      confidence: "estable",
    },
    {
      id: "pen-tool",
      source_app: "Photoshop/Illustrator",
      category: "Vectores",
      aliases: ["pen tool", "pluma", "herramienta pluma"],
      affinity_app: "Affinity Photo/Designer",
      equivalent: "Pen Tool",
      location: "Barra de herramientas",
      shortcut: "P (igual)",
      notes: "Comportamiento de puntos de anclaje/manejadores prácticamente idéntico.",
      confidence: "estable",
    },
    {
      id: "history-panel",
      source_app: "Photoshop",
      category: "Interfaz",
      aliases: ["history panel", "historial", "snapshot"],
      affinity_app: "Affinity (todas)",
      equivalent: "History Panel",
      location: "Ventana > History",
      shortcut: "Ctrl/Cmd+Z para deshacer paso a paso",
      notes: "Mismo concepto de línea de tiempo de pasos, sin límite fijo de historial (según memoria).",
      confidence: "estable",
    },

    // ---------------- ILLUSTRATOR -> AFFINITY DESIGNER ----------------
    {
      id: "artboards",
      source_app: "Illustrator",
      category: "Documento",
      aliases: ["artboards", "mesas de trabajo"],
      affinity_app: "Affinity Designer",
      equivalent: "Artboards (mismo nombre)",
      location: "Herramienta Artboard en la barra de herramientas",
      shortcut: "Igual concepto",
      notes: "Gestión casi idéntica: múltiples mesas de trabajo en un mismo documento.",
      confidence: "estable",
    },
    {
      id: "pathfinder",
      source_app: "Illustrator",
      category: "Vectores",
      aliases: ["pathfinder", "buscatrazos"],
      affinity_app: "Affinity Designer",
      equivalent: "Panel Pathfinder / Boolean Operations",
      location: "Ventana > Pathfinder, o barra de operaciones booleanas en la toolbar contextual",
      shortcut: "Add=Ctrl+Alt+/ Subtract/Intersect/Divide disponibles en el panel",
      notes: "Mismas 4 operaciones booleanas base (Add, Subtract, Intersect, Divide) con resultado equivalente.",
      confidence: "estable",
    },
    {
      id: "live-paint",
      source_app: "Illustrator",
      category: "Color",
      aliases: ["live paint", "pintura activa", "cubo de pintura activa"],
      affinity_app: "Affinity Designer",
      equivalent: "Sin equivalente directo — usar Divide (Pathfinder) + relleno individual por forma",
      location: "Pathfinder > Divide, luego seleccionar y rellenar cada subforma resultante",
      shortcut: "N/A",
      notes:
        "Es la mayor brecha de funcionalidad para ilustradores: no hay 'cubeta activa' inteligente. Divide primero, colorea después.",
      confidence: "workaround",
    },
    {
      id: "blend-tool",
      source_app: "Illustrator",
      category: "Vectores",
      aliases: ["blend tool", "herramienta de mezcla", "object blend"],
      affinity_app: "Affinity Designer",
      equivalent: "Sin equivalente automático — Power Duplicate + interpolación manual",
      location: "Edit > Power Duplicate (Ctrl/Cmd+J) repetido, ajustando transform en cada copia",
      shortcut: "Ctrl/Cmd+J para Power Duplicate",
      notes:
        "No existe un Blend Tool que interpole automáticamente entre dos formas/colores. Power Duplicate repite la última transformación (posición/rotación/escala/color), lo que simula secuencias, pero no mezcla morfológica.",
      confidence: "workaround",
    },
    {
      id: "envelope-distort",
      source_app: "Illustrator",
      category: "Deformación",
      aliases: ["envelope distort", "deformar con envolvente"],
      affinity_app: "Affinity Designer",
      equivalent: "Mesh Warp Tool / Perspective Tool",
      location: "Herramientas > Mesh Warp, o Herramientas > Perspective",
      shortcut: "N/A",
      notes: "Mesh Warp cubre la mayoría de los casos de uso de Envelope Distort con malla libre.",
      confidence: "similar",
    },
    {
      id: "appearance-panel",
      source_app: "Illustrator",
      category: "Interfaz",
      aliases: ["appearance panel", "panel de apariencia"],
      affinity_app: "Affinity Designer",
      equivalent: "Combinación: panel Layers (fx) + panel Stroke + panel Fill",
      location: "Los efectos/relleno/trazo se controlan en paneles separados, no en uno unificado",
      shortcut: "N/A",
      notes: "No hay un panel único; se reparte en 3 paneles. El panel 'Styles' permite guardar combinaciones reutilizables.",
      confidence: "workaround",
    },
    {
      id: "symbols",
      source_app: "Illustrator",
      category: "Reutilización",
      aliases: ["symbols", "símbolos", "simbolos"],
      affinity_app: "Affinity Designer",
      equivalent: "Panel Assets (no vinculado en vivo)",
      location: "Ventana > Assets — arrastra elementos reutilizables ahí",
      shortcut: "N/A",
      notes:
        "Limitación real: los Assets de Affinity NO se actualizan en cascada como los Symbols de Illustrator. Si necesitas instancias vinculadas en vivo, esta es la mayor brecha para trabajo de sistemas de iconos/UI.",
      confidence: "workaround",
    },
    {
      id: "image-trace",
      source_app: "Illustrator",
      category: "Vectorización",
      aliases: ["image trace", "trazado de imagen", "vectorizar"],
      affinity_app: "Affinity Designer",
      equivalent: "Herramienta 'Trace' (vectorización integrada)",
      location: "Selecciona la imagen colocada > barra contextual > 'Trace' (varía según versión)",
      shortcut: "N/A",
      notes: "La ubicación exacta cambió entre versiones de Affinity — confirma el menú en tu versión instalada.",
      confidence: "verificar",
    },
    {
      id: "gradient-mesh",
      source_app: "Illustrator",
      category: "Color",
      aliases: ["gradient mesh", "malla de degradado", "mesh tool"],
      affinity_app: "Affinity Designer",
      equivalent: "Sin equivalente directo — combinar múltiples rellenos de degradado elíptico/lineal superpuestos",
      location: "Panel Fill > tipo 'Elliptical/Radial Gradient', apilando varias formas con transparencia",
      shortcut: "N/A",
      notes: "Para ilustración fotorrealista con mesh complejo, esta es una limitación conocida frente a Illustrator.",
      confidence: "workaround",
    },
    {
      id: "type-on-path",
      source_app: "Illustrator",
      category: "Tipografía",
      aliases: ["type on a path", "texto en trayectoria", "texto en trazado"],
      affinity_app: "Affinity Designer",
      equivalent: "Artistic Text Tool sobre una curva",
      location: "Selecciona la herramienta Artistic Text y haz clic directamente sobre el trazado",
      shortcut: "N/A",
      notes: "Comportamiento muy similar, incluyendo offset y flip del texto respecto a la curva.",
      confidence: "estable",
    },
    {
      id: "perspective-grid",
      source_app: "Illustrator",
      category: "Herramientas",
      aliases: ["perspective grid", "cuadrícula de perspectiva", "rejilla de perspectiva"],
      affinity_app: "Affinity Designer",
      equivalent: "Perspective Tool",
      location: "Herramientas > Perspective",
      shortcut: "N/A",
      notes: "El flujo para dibujar/ajustar en perspectiva es distinto (menos automatizado) pero cubre el mismo objetivo.",
      confidence: "similar",
    },

    // ---------------- EXPORTACIÓN / FORMATOS ----------------
    {
      id: "save-for-web",
      source_app: "Photoshop/Illustrator",
      category: "Exportación",
      aliases: ["save for web", "guardar para web", "export as"],
      affinity_app: "Affinity (todas)",
      equivalent: "Persona de Exportar (Export Persona) + 'Export'",
      location: "Icono de Persona 'Export' en la barra superior",
      shortcut: "Ctrl/Cmd+Alt+Shift+S en algunos contextos",
      notes: "Permite definir 'slices' y presets de exportación múltiple igual que Save for Web, con vista previa lado a lado.",
      confidence: "estable",
    },
    {
      id: "pdf-export",
      source_app: "Illustrator",
      category: "Exportación",
      aliases: ["export pdf", "exportar pdf", "guardar como pdf"],
      affinity_app: "Affinity Designer/Publisher",
      equivalent: "File > Export > PDF",
      location: "Menú File > Export",
      shortcut: "N/A",
      notes: "Soporta PDF/X para imprenta igual que Illustrator.",
      confidence: "estable",
    },
  ];

  return KB;
});
